# This workflow will run tests using node and then cereate a release based on package.json version
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Test

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      # Push events on master branch
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test
      - uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Test run'
          description: 'Passed'
          state: '${{ job.status }}'
          sha: ${{github.event.pull_request.head.sha || github.sha}}
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - run: git config user.name "$GITHUB_ACTOR"
      - run: npm ci
      - run: npm run build
      - run: git add .
      - run: git commit -m "update build" --allow-empty
      - run: git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY"